### ISSUE TITLE
Game crashes to desktop at or soon after Polytron screen

### ISSUE THREAD

**Issue by blackorpheus16** [renaudbedard/fez-1.12-issues#140]
On Windows 7, Steam, my game crashes to desktop as the Polytron logo is coming up (it never did this in the previous version). Sometimes the logo begins to flash like crazy before I get kicked.

Debug Log.txt:

(06:24:08.080) [Version] INFORMATION : 1.12, Build Date : 2016-08-19 21:04:18
(06:24:08.302) [FNA] INFORMATION : IGLDevice: OpenGLDevice
(06:24:08.302) [FNA] INFORMATION : OpenGL Device: Intel(R) HD Graphics 4000
(06:24:08.302) [FNA] INFORMATION : OpenGL Driver: 3.3.0 - Build 8.15.10.2669
(06:24:08.303) [FNA] INFORMATION : OpenGL Vendor: Intel
(06:24:08.303) [FNA] INFORMATION : MojoShader Profile: glsl120
(06:24:08.310) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(06:24:08.331) [Instancing] INFORMATION : Hardware instancing is enabled
(06:24:08.373) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(06:24:08.375) [SettingsManager] INFORMATION : Screen set to {{Width:1366 Height:768 Format:Color}}
(06:24:08.375) [SettingsManager] INFORMATION : Screen mode is : Fullscreen
(06:24:08.375) [SettingsManager] INFORMATION : Backbuffer is 1366x768
(06:24:08.376) [SettingsManager] INFORMATION : VSync is on
(06:24:08.376) [SettingsManager] INFORMATION : Multisample count is 0
(06:24:08.472) [Threading] INFORMATION : Multithreading is enabled
(06:24:09.095) [Intro] INFORMATION : First draw done!
(06:24:09.902) [StaticPreloader] INFORMATION : SharedContentManager preloaded.
(06:24:10.017) [StaticPreloader] INFORMATION : Music library initialized.
(06:24:10.027) [StaticPreloader] INFORMATION : Volume levels loaded.
(06:24:10.104) [StaticPreloader] INFORMATION : Animations filled.
(06:24:10.104) [StaticPreloader] INFORMATION : Text scroll pre-initialized.
(06:24:10.106) [StaticPreloader] INFORMATION : World map pre-initialized.
(06:24:10.106) [StaticPreloader] INFORMATION : Pause menu pre-initialized.
(06:24:10.515) [Intro] INFORMATION : Preloading complete.

Windows "Problem signature":

Problem Event Name: APPCRASH
Application Name:   FEZ.exe
Application Version:    1.12.0.0
Application Timestamp:  57b7ac93
Fault Module Name:  StackHash_e41e
Fault Module Version:   6.1.7601.23418
Fault Module Timestamp: 5708a73e
Exception Code: c0000374
Exception Offset:   000ce843
OS Version: 6.1.7601.2.1.0.768.3
Locale ID:  1033
Additional Information 1:   e41e
Additional Information 2:   e41e128b6abd48ff4879f711384f7421
Additional Information 3:   1b3e
Additional Information 4:   1b3ecccf8fd8ff6db93af5f7ba7f8e09

**Comment by flibitijibibo** [comment]
Looking up the module that crashed (a Windows module called StackHash) it appears DEP does not like the game running on your system. Why that is, I couldn't tell you, but try these steps to add FEZ.exe to the exception list:

http://www.thewindowsclub.com/turn-off-data-execution-prevention-dep

Considering the behavior of the visuals it could be the graphics driver doing something that trips DEP. Updating the graphics driver could be a safer bet, but that assumes my guess is correct.

**Comment by flibitijibibo** [comment]
Looked up the driver version, just so you know your driver's from ~April 2012. There's a newer version over here:

https://downloadcenter.intel.com/product/81499/Intel-HD-Graphics-4000-for-3rd-Generation-Intel-Core-Processors

**Comment by blackorpheus16** [comment]
Interesting. I tried to turn off DEP for the game and got this message: "This program must run with data execution protection (DEP) enabled. You cannot turn off DEP for this program."

I also can't seem to update my graphics driver because "A customized computer manufacturer driver is installed on your computer." I have a laptop from HP :/

Thank you so much for looking at this. Do you happen to have any other suggestions?

**Comment by flibitijibibo** [comment]
It looks like you can get around the HP issue by uninstalling the manufacturer driver first:

http://www.intel.com/content/www/us/en/support/graphics-drivers/000005469.html

Hopefully that'll fix it. Shame we can't drop DEP for the game, particularly considering it's using .NET and should be perfectly "safe" by Windows' own standards... then again I shouldn't have to make people drop security features for a game, so let's focus on the driver for now.

**Comment by Nicholas-Steel** [comment]
I encountered a perpetual loading screen (No in-game error message or crash) with the yellow loading cube constantly spinning in the bottom right corner. This problem was encountered in the previous Experimental build (The version before the current version available on Steam)

(12:19:45.139) [FNA] INFORMATION : Controller 0: Generic DirectInput Controller
(12:19:45.889) [Version] INFORMATION : 1.12, Build Date : 2016-08-23 23:19:43
(12:19:46.065) [FNA] INFORMATION : IGLDevice: OpenGLDevice
(12:19:46.067) [FNA] INFORMATION : OpenGL Device: GeForce GTX 760/PCIe/SSE2
(12:19:46.068) [FNA] INFORMATION : OpenGL Driver: 4.5.0 NVIDIA 372.54
(12:19:46.069) [FNA] INFORMATION : OpenGL Vendor: NVIDIA Corporation
(12:19:46.070) [FNA] INFORMATION : MojoShader Profile: glsl120
(12:19:46.078) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(12:19:46.103) [Instancing] INFORMATION : Hardware instancing is enabled
(12:19:46.138) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(12:19:46.141) [SettingsManager] INFORMATION : Screen set to {{Width:1920 Height:1080 Format:Color}}
(12:19:46.143) [SettingsManager] INFORMATION : Screen mode is : Fullscreen
(12:19:46.145) [SettingsManager] INFORMATION : Backbuffer is 1920x1080
(12:19:46.147) [SettingsManager] INFORMATION : VSync is on
(12:19:46.149) [SettingsManager] INFORMATION : Multisample count is 0
(12:19:46.246) [Threading] INFORMATION : Multithreading is enabled
(12:19:46.827) [Intro] INFORMATION : First draw done!
(12:19:48.499) [StaticPreloader] INFORMATION : SharedContentManager preloaded.
(12:19:50.266) [StaticPreloader] INFORMATION : Music library initialized.
(12:19:50.286) [StaticPreloader] INFORMATION : Volume levels loaded.
(12:19:50.373) [StaticPreloader] INFORMATION : Animations filled.
(12:19:50.376) [StaticPreloader] INFORMATION : Text scroll pre-initialized.
(12:19:50.377) [StaticPreloader] INFORMATION : World map pre-initialized.
(12:19:50.379) [StaticPreloader] INFORMATION : Pause menu pre-initialized.
(12:19:50.893) [Intro] INFORMATION : Preloading complete.
(12:20:05.098) [Intro] INFORMATION : Level load complete.
(12:20:10.914) [Intro] INFORMATION : Intro is done and game is go!
(12:37:43.966) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(12:37:43.967) [SettingsManager] INFORMATION : Screen set to {{Width:1920 Height:1080 Format:Color}}
(12:37:43.969) [SettingsManager] INFORMATION : Screen mode is : Fullscreen
(12:37:43.970) [SettingsManager] INFORMATION : Backbuffer is 1920x1080
(12:37:43.972) [SettingsManager] INFORMATION : VSync is on
(12:37:43.973) [SettingsManager] INFORMATION : Multisample count is 0
(12:49:49.691) [Unhandled Exception] ERROR : System.ArgumentOutOfRangeException: Index must be within the bounds of the List.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Microsoft.Xna.Framework.GameComponentCollection.InsertItem(Int32 index, IGameComponent item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at FezEngine.Tools.ServiceHelper.AddComponent(IGameComponent component, Boolean addServices)
   at FezEngine.Components.NpcHost.LoadCharacters()
   at System.Action.Invoke()
   at FezEngine.Services.LevelManager.OnLevelChanged()
   at FezGame.Services.GameLevelManager.ChangeLevel(String levelName)
   at FezGame.Components.Actions.EnterDoor.DoLoad(Boolean dummy)
   at FezEngine.Tools.Worker`1.Act()
   at FezEngine.Tools.PersistentThread.DoActualWork()
   at Common.Logger.Try(Action action)
