### ISSUE TITLE
debug log (guy from twitter)

### ISSUE THREAD

**Issue by jack-clare208** [renaudbedard/fez-1.12-issues#167]
there's a couple of these debug logs from the time of that crash, both of which are different.

debug log one:

(08:05:41.291) [Version] INFORMATION : 1.12, Build Date : 2016-08-20 14:50:53
(08:05:41.797) [FNA] INFORMATION : IGLDevice: OpenGLDevice
(08:05:41.799) [FNA] INFORMATION : OpenGL Device: Intel(R) HD Graphics 520
(08:05:41.800) [FNA] INFORMATION : OpenGL Driver: 4.4.0 - Build 20.19.15.4312
(08:05:41.801) [FNA] INFORMATION : OpenGL Vendor: Intel
(08:05:41.802) [FNA] INFORMATION : MojoShader Profile: glsl120
(08:05:41.821) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(08:05:41.895) [Instancing] INFORMATION : Hardware instancing is enabled
(08:05:41.967) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(08:05:41.972) [SettingsManager] INFORMATION : Screen set to {{Width:1920 Height:1080 Format:Color}}
(08:05:41.974) [SettingsManager] INFORMATION : Screen mode is : Fullscreen
(08:05:41.976) [SettingsManager] INFORMATION : Backbuffer is 1920x1080
(08:05:41.980) [SettingsManager] INFORMATION : VSync is on
(08:05:41.982) [SettingsManager] INFORMATION : Multisample count is 0
(08:05:42.383) [Threading] INFORMATION : Multithreading is enabled
(08:05:44.065) [Intro] INFORMATION : First draw done!
(08:05:46.330) [StaticPreloader] INFORMATION : SharedContentManager preloaded.
(08:05:48.946) [StaticPreloader] INFORMATION : Music library initialized.
(08:05:49.023) [StaticPreloader] INFORMATION : Volume levels loaded.
(08:05:49.353) [StaticPreloader] INFORMATION : Animations filled.
(08:05:49.357) [StaticPreloader] INFORMATION : Text scroll pre-initialized.
(08:05:49.360) [StaticPreloader] INFORMATION : World map pre-initialized.
(08:05:49.365) [StaticPreloader] INFORMATION : Pause menu pre-initialized.
(08:05:50.129) [Unhandled Exception] ERROR : System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at FezEngine.Tools.TimeInterpolation.ProcessCallbacks(GameTime gameTime)
   at FezGame.Fez.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at FezGame.Program.MainInternal()
   at Common.Logger.Try(Action action)
(08:05:50.523) [Intro] INFORMATION : Preloading complete.
(08:05:51.061) [FEZ] INFORMATION : Exiting.

debug log 2:

(08:06:10.747) [Version] INFORMATION : 1.12, Build Date : 2016-08-20 14:50:53
(08:06:11.190) [FNA] INFORMATION : IGLDevice: OpenGLDevice
(08:06:11.191) [FNA] INFORMATION : OpenGL Device: Intel(R) HD Graphics 520
(08:06:11.192) [FNA] INFORMATION : OpenGL Driver: 4.4.0 - Build 20.19.15.4312
(08:06:11.193) [FNA] INFORMATION : OpenGL Vendor: Intel
(08:06:11.194) [FNA] INFORMATION : MojoShader Profile: glsl120
(08:06:11.213) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(08:06:11.285) [Instancing] INFORMATION : Hardware instancing is enabled
(08:06:11.362) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(08:06:11.368) [SettingsManager] INFORMATION : Screen set to {{Width:1920 Height:1080 Format:Color}}
(08:06:11.370) [SettingsManager] INFORMATION : Screen mode is : Fullscreen
(08:06:11.373) [SettingsManager] INFORMATION : Backbuffer is 1920x1080
(08:06:11.376) [SettingsManager] INFORMATION : VSync is on
(08:06:11.378) [SettingsManager] INFORMATION : Multisample count is 0
(08:06:11.743) [Threading] INFORMATION : Multithreading is enabled
(08:06:13.492) [Intro] INFORMATION : First draw done!
(08:06:14.258) [StaticPreloader] INFORMATION : SharedContentManager preloaded.
(08:06:14.607) [StaticPreloader] INFORMATION : Music library initialized.
(08:06:14.643) [StaticPreloader] INFORMATION : Volume levels loaded.
(08:06:14.879) [StaticPreloader] INFORMATION : Animations filled.
(08:06:14.882) [StaticPreloader] INFORMATION : Text scroll pre-initialized.
(08:06:14.885) [StaticPreloader] INFORMATION : World map pre-initialized.
(08:06:14.887) [StaticPreloader] INFORMATION : Pause menu pre-initialized.
(08:06:16.027) [Intro] INFORMATION : Preloading complete.
(08:06:34.707) [Content] INFORMATION : Room DRUM does not have a map image!
(08:06:34.764) [Content] INFORMATION : Room DRUM does not have a map image!
(08:06:45.239) [Intro] INFORMATION : Level load complete.
(08:06:57.731) [Intro] INFORMATION : Intro is done and game is go!
(08:11:00.272) [Intro] INFORMATION : Level load complete.
(08:11:13.803) [Intro] INFORMATION : Intro is done and game is go!
(08:12:34.890) [FEZ] INFORMATION : Exiting.

hope this is helpful!

**Comment by flibitijibibo** [comment]
The first one might be fixed by just disabling threading, but the second one is a weird one... it almost looks like it's loading the level twice at the same time?! That could also be threading maybe, but that's entirely a guess.

**Comment by renaudbedard** [comment]
Taking steps to fix the first issue in the next update. Second one is still a mystery to me!
