### ISSUE TITLE
MojoShader loading issue with specific Windows setup

### ISSUE THREAD

**Issue by 0x0ade** [renaudbedard/fez-1.12-issues#96]
Happens on my PC with Windows 8.1, with both FEZMod enabled and completely uninstalled. MojoShader.dll exists, so it seems to be a dependency issue. This PC already had some OpenGL driver issues, but 1.11 detects a functional OpenGL 3.3 context.

---

JAFM Log, 1.12-debug, FEZMod (invariant UI culture):

```
(21:51:51.844) [FEZMod] JustAnotherFEZMod (FEZMod) 0.3a8
(21:51:51.871) [FEZMod] Running .NET 4.5+ codepath for setting the default culture.
(21:51:52.055) [FEZMod] Initializing FEZ mods...
(21:51:52.062) [FEZMod] Found referenced assembly mscorlib
(21:51:52.088) [FEZMod] Found referenced assembly System.Data.SqlXml
(21:51:52.149) [FEZMod] Found referenced assembly System.Xml
(21:51:52.161) [FEZMod] Found referenced assembly System.Security
(21:51:52.171) [FEZMod] Found referenced assembly System.Configuration
(21:51:52.178) [FEZMod] Found referenced assembly System
(21:51:52.192) [FEZMod] Found referenced assembly System.Numerics
(21:51:52.199) [FEZMod] Found referenced assembly System.Core
(21:51:52.211) [FEZMod] Found referenced assembly FNA
(21:51:52.283) [FEZMod] Found referenced assembly SimpleDefinitionLanguage
(21:51:52.289) [FEZMod] Found referenced assembly Common
(21:51:52.296) [FEZMod] Found referenced assembly ContentSerialization
(21:51:52.306) [FEZMod] Found referenced assembly System.Drawing
(21:51:52.317) [FEZMod] Found referenced assembly XnaWordWrapCore
(21:51:52.324) [FEZMod] Found referenced assembly FezEngine
(21:51:52.483) [FEZMod] Pre-Initializing FEZMod.Engine
(21:51:52.501) [FEZMod] Found referenced assembly Accessibility
(21:51:52.542) [FEZMod] Found referenced assembly System.Deployment
(21:51:52.602) [FEZMod] Found referenced assembly System.Runtime.Serialization.Formatters.Soap
(21:51:52.631) [FEZMod] Found referenced assembly System.Windows.Forms
(21:51:52.646) [FEZMod] Found referenced assembly Steamworks.NET
(21:51:52.693) [FEZMod] Found referenced assembly EasyStorage
(21:51:52.710) [FEZMod] Found referenced assembly Mono.Cecil
(21:51:52.756) [FEZMod] Found referenced assembly MonoMod
(21:51:52.766) [FEZMod] Found referenced assembly FEZ
(21:51:52.882) [FEZMod] Pre-Initializing FEZDroid
(21:51:52.998) [FEZDroid] Checking if running in Android
(21:51:53.015) [FEZMod] Checking for custom arguments...
(21:51:53.035) [FEZMod] Found -pphd / --pixel-perfect-high-definition
(21:51:53.047) [FEZMod] Passing to FEZ...
(21:51:54.482) [FEZMod] Handling FEZ crash...
(21:51:54.497) [FEZMod] System.DllNotFoundException: Unable to load DLL 'MojoShader.dll': Das angegebene Modul wurde nicht gefunden. (Exception from HRESULT: 0x8007007E)
   at MojoShader.INTERNAL_glBestProfile(MOJOSHADER_glGetProcAddress lookup, IntPtr lookup_d, MOJOSHADER_malloc m, MOJOSHADER_free f, IntPtr malloc_d)
   at MojoShader.MOJOSHADER_glBestProfile(MOJOSHADER_glGetProcAddress lookup, IntPtr lookup_d, MOJOSHADER_malloc m, MOJOSHADER_free f, IntPtr malloc_d)
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice..ctor(PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.get_GraphicsDevice()
   at Microsoft.Xna.Framework.Game.get_GraphicsDevice()
   at Microsoft.Xna.Framework.GamePlatform.BeforeInitialize()
   at Microsoft.Xna.Framework.SDL2_GamePlatform.BeforeInitialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at FezGame.Program.orig_MainInternal()
   at FezGame.Program.MainInternal()
(21:51:54.530) [FEZMod] TypeLoadException.TypeName: 
```

Weirdly this is also where FEZMod ends. The German error translates to "The specified module could not be found"; FEZMod sets the main thread UI culture to CultureInfo.InvariantCulture to help with the error messages, but that one either comes from another thread or somewhere deeper.

---

Debug Log, 1.12-debug, no FEZMod (default UI culture):
The Debug Log doesn't change with this build, indicating some harder failure.

---

Debug Log, fna-unstable, no FEZMod (default UI culture):

```
(21:56:04.837) [Version] INFORMATION : 1.12, Build Date : 2015-12-20 9:50:28 PM
(21:56:05.389) [Unhandled Exception] ERROR : System.DllNotFoundException: Die DLL "MojoShader.dll": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
   bei MojoShader.INTERNAL_glBestProfile(MOJOSHADER_glGetProcAddress lookup, IntPtr lookup_d, MOJOSHADER_malloc m, MOJOSHADER_free f, IntPtr malloc_d)
   bei Microsoft.Xna.Framework.Graphics.OpenGLDevice..ctor(PresentationParameters presentationParameters)
   bei Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   bei Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   bei Microsoft.Xna.Framework.GraphicsDeviceManager.get_GraphicsDevice()
   bei Microsoft.Xna.Framework.Game.get_GraphicsDevice()
   bei Microsoft.Xna.Framework.GamePlatform.BeforeInitialize()
   bei Microsoft.Xna.Framework.SDL2_GamePlatform.BeforeInitialize()
   bei Microsoft.Xna.Framework.Game.DoInitialize()
   bei Microsoft.Xna.Framework.Game.Run()
   bei FezGame.Program.MainInternal()
   bei Common.Logger.Try(Action action)
(21:56:05.389) [FEZ] INFORMATION : Exiting.
```

**Comment by renaudbedard** [comment]
See #11; you need to install the VC++2015 redist for x86 (32-bit) as well as .NET 4.6.x (the latest).
Let me know if that does not fix it though!

**Comment by 0x0ade** [comment]
Yup, installing VC++2015 fixed it. Whoops - I was sure I already had it installed, but as it seems I only installed .NET 4.6 some time ago :/
